'use client';
import {useEffect,useState} from 'react';
import {Bean as BeanIcon,BookOpen,ChartNoAxesCombined,Settings,Coffee,Plus,Search,Sun,Moon,ArrowUpRight,Star,Download,WifiOff,Leaf,Pencil,Trash2,FlaskConical} from 'lucide-react';
import {Bean,Recipe,Data,empty,demo,readData,writeData,download,ratio,duration,methods} from '@/lib/coffee';
import CoffeeForm from '@/components/coffee-form';import CloudSettings from '@/components/cloud-settings';
const tabs=[{id:'journal',name:'El cuaderno',icon:BookOpen},{id:'beans',name:'Mis cafés',icon:BeanIcon},{id:'analysis',name:'Análisis',icon:ChartNoAxesCombined},{id:'settings',name:'Ajustes',icon:Settings}];
export default function Home(){
 const [tab,setTab]=useState('journal');const [data,setData]=useState<Data>(empty);const [isDemo,setDemo]=useState(false);const [ready,setReady]=useState(false);const [dark,setDark]=useState(false);const [offline,setOffline]=useState(false);const [query,setQuery]=useState('');const [method,setMethod]=useState('Todos');const [coffee,setCoffee]=useState('Todos');const [modal,setModal]=useState<{kind:'bean'|'recipe';initial?:Bean|Recipe}|null>(null);const [message,setMessage]=useState('');
 useEffect(()=>{try{setData(readData());setDark(localStorage.getItem('savia-theme')==='dark')}catch{setMessage('No se pudieron leer los datos locales. No se sobrescribirán hasta que guardes un cambio.')}if(window.location.hash.includes('access_token=')){window.history.replaceState(null,'',window.location.pathname);setMessage('Correo confirmado. Entra en Ajustes e inicia sesión para guardar en la nube.')}setReady(true);const status=()=>setOffline(!navigator.onLine);status();window.addEventListener('online',status);window.addEventListener('offline',status);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>setMessage('El modo offline no está disponible en este navegador.'));return()=>{window.removeEventListener('online',status);window.removeEventListener('offline',status)}},[]);
 function save(next:Data){try{if(isDemo){setData(next);setMessage('Ejemplo actualizado. Tus datos personales no han cambiado.')}else{writeData(next);setData(next);setMessage('Guardado en este dispositivo.')}return true}catch{setMessage('No se pudo guardar. Exporta tus datos para conservarlos.');return false}}
 function newRecipe(){if(!data.beans.length){setMessage('Añade primero el café que vas a preparar.');setModal({kind:'bean'})}else setModal({kind:'recipe'})}
 function switchDemo(){if(isDemo){try{setData(readData());setDemo(false)}catch{setMessage('Error al recuperar tus datos')}}else{setData(structuredClone(demo));setDemo(true)}setCoffee('Todos');setMethod('Todos')}
 const recipes=data.recipes.filter(r=>(method==='Todos'||r.method===method)&&(coffee==='Todos'||r.beanId===coffee)&&((data.beans.find(b=>b.id===r.beanId)?.name||'')+' '+r.notes).toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.date.localeCompare(a.date));
 const best=[...recipes].sort((a,b)=>b.score-a.score)[0];const bestBean=data.beans.find(b=>b.id===best?.beanId);const avg=data.recipes.length?(data.recipes.reduce((s,r)=>s+r.score,0)/data.recipes.length).toFixed(1):'—';
 function exportData(format:'csv'|'json'){download(data,format);setMessage('Exportación preparada.')}
 const filters=<div className="filters"><div className="search"><Search size={18}/><input aria-label="Buscar recetas" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar un café o una nota…"/></div><select aria-label="Filtrar por café" value={coffee} onChange={e=>setCoffee(e.target.value)}><option value="Todos">Todos los cafés</option>{data.beans.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><select aria-label="Filtrar por método" value={method} onChange={e=>setMethod(e.target.value)}><option value="Todos">Todos los métodos</option>{methods.map(m=><option key={m}>{m}</option>)}</select></div>;
 return <div className={dark?'app dark':'app'}><aside className="sidebar"><a className="brand" href="#" onClick={()=>setTab('journal')}><span className="brand-icon"><Coffee size={25}/></span>savia<span className="brand-dot">.</span></a><div className="brand-caption">UN CAFÉ. UN DESCUBRIMIENTO.</div><nav>{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon size={21}/><span>{t.name}</span>{tab===t.id&&<span className="nav-mark"/>}</button>)}</nav><div className="sidebar-foot"><Leaf size={23}/><p>El mejor café es el que<br/>aprendes a preparar.</p><span>SAVIA / CUADERNO PERSONAL</span></div></aside>
 <main><header className="topbar"><span>Tu espacio para el café de especialidad</span><div className="actions"><span className="local-label">{offline?<><WifiOff size={15}/> Sin conexión</>:<>Guardado local</>}</span><button className="icon-button" aria-label={dark?'Activar modo claro':'Activar modo oscuro'} onClick={()=>{setDark(!dark);localStorage.setItem('savia-theme',!dark?'dark':'light')}}>{dark?<Sun size={20}/>:<Moon size={20}/>}</button><span className="avatar">S</span></div></header>
 <div className="content"><div className="page-heading"><div><span className="eyebrow">EL RITUAL DE CADA DÍA</span><h1>{tabs.find(t=>t.id===tab)?.name}</h1><p>{tab==='journal'?'Cada taza cuenta una historia. Guarda la tuya.':tab==='beans'?'El origen de tu próxima gran taza.':tab==='analysis'?'Pequeños ajustes. Mejores descubrimientos.':'Tu cuaderno, a tu manera.'}</p></div>{tab!=='settings'&&<button className="button" onClick={tab==='beans'?()=>setModal({kind:'bean'}):newRecipe}><Plus size={18}/>{tab==='beans'?'Añadir café':'Nueva receta'}</button>}</div>
 <div className="demo-bar"><span><FlaskConical size={16}/>{isDemo?'Estás explorando datos ficticios de ejemplo.':'Tus cafés y recetas se guardan en este dispositivo.'}</span><button onClick={switchDemo}>{isDemo?'Volver a mis datos':'Explorar ejemplo'}</button></div>
 {(tab==='journal'||tab==='analysis')&&<><div className="stats"><div><span>RECETAS GUARDADAS</span><strong>{String(data.recipes.length).padStart(2,'0')}<BookOpen/></strong><small>Cada prueba, un aprendizaje</small></div><div><span>CAFÉS EN TU COLECCIÓN</span><strong>{String(data.beans.length).padStart(2,'0')}<BeanIcon/></strong><small>Orígenes por descubrir</small></div><div><span>PUNTUACIÓN MEDIA</span><strong>{avg}<span className="outof">/ 10</span><Star/></strong><small>Tu criterio, tu mejor referencia</small></div></div></>}
 {tab==='journal'&&<div className="journal-layout"><section><div className="section-heading"><h2>Tus extracciones</h2><span>{recipes.length} registros</span></div>{filters}<div className="recipe-list">{recipes.map(r=>{const b=data.beans.find(b=>b.id===r.beanId);return <button className="recipe-card" key={r.id} onClick={()=>setModal({kind:'recipe',initial:r})}><div className={'method-icon '+(r.method==='Espresso'?'espresso':'')}><Coffee size={29}/><span>{r.method}</span></div><div className="recipe-main"><span className="card-meta">{b?.origin} <span>· {r.date.split('-').reverse().join('.')}</span></span><h3>{b?.name||'Café eliminado'}</h3><p>{b?.roaster} <span>· {b?.process}</span></p><div className="recipe-values"><span>{r.dose} g <span className="muted">/ {r.method==='Espresso'?r.output:r.water} g</span></span><span>1:{ratio(r)}</span><span>{r.temperature} °C</span><span>{duration(r.seconds)}</span></div></div><div className="recipe-score"><Star size={14}/><strong>{r.score.toFixed(1)}</strong><ArrowUpRight size={17}/></div></button>})}{!recipes.length&&<div className="empty"><Coffee size={38}/><h3>{data.recipes.length?'No hay coincidencias':'Tu próxima taza empieza aquí'}</h3><p>{data.recipes.length?'Prueba otro café, método o búsqueda.':'Añade un café y registra tu primera extracción.'}</p><button className="button secondary" onClick={newRecipe}>Registrar una receta</button></div>}</div></section><aside className="journal-aside"><div className="best-card"><span className="eyebrow"><Star size={15}/> TU TAZA DESTACADA</span><h2>{bestBean?.name||'Un hallazgo por descubrir'}</h2><p>{best?`${bestBean?.origin} · ${best.method}`:'Tu receta mejor puntuada aparecerá aquí.'}</p>{best&&<><div className="big-score">{best.score.toFixed(1)}<span>/ 10</span></div><div className="best-specs"><div><strong>{best.temperature}°</strong><span>Temperatura</span></div><div><strong>{best.clicks}</strong><span>Ajuste del molino</span></div><div><strong>1:{ratio(best)}</strong><span>Ratio</span></div></div><p className="best-notes">“{best.notes.slice(0,160)}{best.notes.length>160?'…':''}”</p><button onClick={()=>setModal({kind:'recipe',initial:best})}>Ver receta <ArrowUpRight size={16}/></button></>}</div><div className="collection-preview"><div className="section-heading"><h2>En tu estantería</h2><button aria-label="Ver mis cafés" className="icon-button" onClick={()=>setTab('beans')}><ArrowUpRight size={18}/></button></div>{data.beans.slice(0,3).map((b,i)=><button key={b.id} className="mini-bean" onClick={()=>setModal({kind:'bean',initial:b})}><span className={'bean-number color-'+i}>0{i+1}</span><span><strong>{b.name}</strong><small>{b.roaster} · {b.process}</small></span></button>)}{!data.beans.length&&<p>Aún no has añadido ningún café.</p>}</div><div className="note"><span>NOTA AL MARGEN</span><p>Una variable cada vez.<br/>Así empiezan los grandes cafés.</p></div></aside></div>}
 {tab==='beans'&&<div className="beans-grid">{data.beans.map((b,i)=><article className="bean-card" key={b.id}><header><span className={'bean-number color-'+i%3}><BeanIcon/></span><span className="tag">{b.process||'Sin proceso'}</span></header><span className="eyebrow">{b.origin}</span><h2>{b.name}</h2><p>{b.roaster}</p><dl>{[['Productor',b.producer],['Variedad',b.variety],['Altura',b.altitude?b.altitude+' m':'—'],['Tueste',b.roastDate||'—']].map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v||'—'}</dd></div>)}</dl><p className="tasting">{b.notes||'Sin notas de cata'}</p><footer><button className="text-button" onClick={()=>setModal({kind:'bean',initial:b})}><Pencil size={16}/> Editar café</button><button className="icon-button" aria-label={'Eliminar '+b.name} onClick={()=>{if(data.recipes.some(r=>r.beanId===b.id)){setMessage('Este café tiene recetas. Elimínalas primero para conservar la relación de tus datos.');return}if(confirm(`¿Eliminar ${b.name}?`))save({...data,beans:data.beans.filter(x=>x.id!==b.id)})}}><Trash2 size={17}/></button></footer></article>)}{!data.beans.length&&<div className="empty full"><BeanIcon size={38}/><h2>Una estantería por llenar</h2><p>Empieza con el café que tienes en casa.</p><button className="button" onClick={()=>setModal({kind:'bean'})}>Añadir mi primer café</button></div>}</div>}
 {tab==='analysis'&&<>{filters}<div className="analysis-grid"><section className="panel"><span className="eyebrow">RESULTADOS OBSERVADOS</span><h2>Tu mejor receta en esta selección</h2>{best?<><h3>{bestBean?.name} · {best.method}</h3><p>Tu receta mejor puntuada obtuvo <strong>{best.score}/10</strong>, a <strong>{best.temperature} °C</strong> y con un ajuste de <strong>{best.clicks}</strong> en {best.grinder}.</p><p className="muted">{recipes.length} extracciones en la selección. Es un resultado personal, no una relación causal. Filtra por café y método para comparar.</p><button className="button secondary" onClick={()=>setModal({kind:'recipe',initial:best})}>Abrir receta</button></>:<p>Registra una receta para descubrir tus mejores resultados.</p>}</section><section className="panel"><h2>Perfil de tu mejor taza</h2>{(['acidity','sweetness','body','finish'] as const).map((k,i)=><div className="bar-row" key={k}><span>{['Acidez','Dulzor','Cuerpo','Postgusto'][i]}</span><div className="bar-track"><div style={{width:(best?.[k]||0)*10+'%'}}/></div><strong>{best?.[k]||'—'}</strong></div>)}</section><section className="panel full"><div className="section-heading"><h2>Comparar extracciones</h2><div className="actions"><button className="text-button" onClick={()=>exportData('csv')}><Download size={16}/> CSV</button><button className="text-button" onClick={()=>exportData('json')}>JSON completo</button></div></div><div className="table-wrap"><table><thead><tr>{['Café / método','Fecha','Temperatura','Molino / ajuste','Ratio','Tiempo','Puntuación'].map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{recipes.map(r=><tr key={r.id}><td>{data.beans.find(b=>b.id===r.beanId)?.name}<small>{r.method}</small></td><td>{r.date}</td><td>{r.temperature} °C</td><td>{r.grinder} / {r.clicks}</td><td>1:{ratio(r)}</td><td>{duration(r.seconds)}</td><td><strong>{r.score}/10</strong></td></tr>)}</tbody></table></div>{!recipes.length&&<p>Sin extracciones para esta selección.</p>}<small>La exportación incluye todas las recetas; JSON incluye también el inventario.</small></section></div></>}
 {tab==='settings'&&<div className="settings-layout"><section className="panel"><h2>Tu copia de seguridad</h2><p>Exporta tus registros periódicamente. Borrar los datos del navegador también borra la copia local.</p><div className="actions"><button className="button secondary" onClick={()=>exportData('json')}><Download size={17}/> Exportar JSON</button><button className="button secondary" onClick={()=>exportData('csv')}>Exportar CSV</button></div><h3>Instalar Savia</h3><p>En el navegador, abre el menú y elige «Instalar aplicación» o «Añadir a pantalla de inicio». Abre la app una vez con conexión antes de usarla offline.</p><h3>Sobre tus datos</h3><p>El ratio de filtro usa el agua añadida; el de espresso usa la bebida obtenida. Las puntuaciones sensoriales van de 1 a 10.</p></section>{ready&&!isDemo&&<CloudSettings data={data} onLoad={d=>{if(!save(d))throw new Error('No se pudo guardar la copia local')}}/>}{isDemo&&<section className="panel"><h2>Modo de ejemplo</h2><p>Vuelve a tus datos para conectar tu cuenta y guardar en la nube.</p></section>}</div>}
 <footer className="page-footer"><span>Savia · Hecho para saborear el proceso</span><span>Una taza a la vez.</span></footer></div></main>
 <nav className="bottom-nav">{tabs.map(t=><button key={t.id} className={tab===t.id?'active':''} onClick={()=>setTab(t.id)}><t.icon size={22}/>{t.name}</button>)}</nav>
 {message&&<div className="toast" role="status"><span>{message}</span><button aria-label="Cerrar aviso" onClick={()=>setMessage('')}>×</button></div>}
 {modal&&<CoffeeForm kind={modal.kind} initial={modal.initial} beans={data.beans} onClose={()=>setModal(null)} onDelete={modal.kind==='recipe'&&modal.initial?()=>{if(confirm('¿Eliminar esta receta?')){if(save({...data,recipes:data.recipes.filter(r=>r.id!==modal.initial?.id)}))setModal(null)}}:undefined} onSave={v=>{const key=modal.kind==='bean'?'beans':'recipes';const list=data[key] as (Bean|Recipe)[];const next={...data,[key]:list.some(x=>x.id===v.id)?list.map(x=>x.id===v.id?v:x):[v,...list]};if(save(next as Data))setModal(null)}}/>}

 </div>
}
