'use client';
import {useState} from 'react';import * as cloud from '@/lib/cloud';import {Data} from '@/lib/coffee';
export default function CloudSettings({data,onLoad}:{data:Data;onLoad:(data:Data)=>void}){
 const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);const [signed,setSigned]=useState(cloud.isSigned);const [revision,setRevision]=useState(cloud.revision);const [cfg,setCfg]=useState(cloud.config);
 async function run(fn:()=>Promise<void>){setBusy(true);try{await fn()}catch(e){setMessage((e as Error).message)}finally{setBusy(false)}}
 return <section className="panel cloud"><h2>Tu cuenta y copia en la nube</h2><p>Crea una cuenta o inicia sesión para guardar tus recetas entre dispositivos. Pulsa «Guardar en la nube» para enviar tus cambios.</p><details><summary>Configuración avanzada de conexión</summary><form onSubmit={e=>{e.preventDefault();try{cloud.configure(cfg.url,cfg.key);setSigned(false);setRevision(0);setMessage('Conexión configurada. Inicia sesión.')}catch(e){setMessage((e as Error).message)}}}><label>URL del proyecto<input type="url" required value={cfg.url} onChange={e=>setCfg({...cfg,url:e.target.value})} placeholder="https://tu-proyecto.supabase.co"/></label><label>Clave pública (publishable o anon)<input required value={cfg.key} onChange={e=>setCfg({...cfg,key:e.target.value})}/></label><small>No uses una clave secreta ni service_role.</small><button className="button secondary">Guardar configuración</button></form></details>
 {!signed?<form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const signup=(e.nativeEvent as SubmitEvent).submitter?.getAttribute('value')==='signup';run(async()=>{const ok=await cloud.login(String(f.get('email')),String(f.get('password')),signup);setSigned(ok);setRevision(cloud.revision());setMessage(ok?'Sesión iniciada. Recupera tu copia antes de editar en un nuevo dispositivo.':'Revisa tu correo para confirmar la cuenta y después inicia sesión.');})}}><div className="form-grid"><label>Correo<input name="email" type="email" autoComplete="email" required/></label><label>Contraseña<input name="password" type="password" minLength={8} autoComplete="current-password" required/></label></div><div className="actions"><button disabled={busy} className="button" value="login">Entrar</button><button disabled={busy} className="button secondary" value="signup">Crear cuenta</button></div></form>:<div className="actions"><button disabled={busy} className="button" onClick={()=>run(async()=>{const rev=await cloud.push(data,revision);setRevision(rev);setMessage('Copia guardada en la nube.');})}>Guardar en la nube</button><button disabled={busy} className="button secondary" onClick={()=>{if(confirm('Se sustituirán los datos de este dispositivo. Exporta un JSON antes si quieres conservarlos.'))run(async()=>{const row=await cloud.pull();if(!row){setRevision(0);setMessage('Todavía no hay una copia en la nube.');return}if(row.data.version!==1||!Array.isArray(row.data.beans)||!Array.isArray(row.data.recipes))throw new Error('Copia no compatible');onLoad(row.data);setRevision(row.revision);setMessage('Copia recuperada.');})}}>Recuperar copia</button><button className="text-button" onClick={()=>{cloud.logout();setSigned(false);setRevision(0);setMessage('Sesión cerrada')}}>Cerrar sesión</button></div>}
 <p role="status">{busy?'Conectando…':message}</p></section>
}
