'use client';
import {useState,useRef,useEffect} from 'react';
import {X} from 'lucide-react';
import {Bean,Recipe,methods,ratio} from '@/lib/coffee';
type Props={kind:'bean'|'recipe';beans:Bean[];initial?:Bean|Recipe;onClose:()=>void;onSave:(v:Bean|Recipe)=>void;onDelete?:()=>void};
export default function CoffeeForm({kind,beans,initial,onClose,onSave,onDelete}:Props){
 const dialog=useRef<HTMLDialogElement>(null);
 const [r,setR]=useState<Recipe>((initial as Recipe)||{id:crypto.randomUUID(),beanId:beans[0]?.id||'',date:new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,10),method:'V60',dose:15,water:250,output:215,seconds:165,temperature:93,grinder:'',clicks:16,score:7,acidity:5,sweetness:5,body:5,finish:5,notes:''});
 useEffect(()=>{const previous=document.body.style.overflow; document.body.style.overflow='hidden';dialog.current?.showModal();return()=>{document.body.style.overflow=previous}},[]);
 const b=initial as Bean|undefined;
 const number=(key:keyof Recipe,label:string,min:number,max:number,step=1)=><label>{label}<input required type="number" min={min} max={max} step={step} value={r[key]} onChange={e=>setR({...r,[key]:e.target.value===''?'':Number(e.target.value)})}/></label>;
 return <dialog ref={dialog} aria-labelledby="coffee-form-title" onCancel={onClose}><form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);onSave(kind==='recipe'?r:{id:b?.id||crypto.randomUUID(),...Object.fromEntries(f)} as Bean)}}><header className="modal-head"><div><span className="eyebrow">TU RITUAL, A TU MANERA</span><h2 id="coffee-form-title">{initial?'Editar':kind==='bean'?'Añadir':'Nueva'} {kind==='bean'?'café':'receta'}</h2></div><button type="button" className="icon-button" aria-label="Cerrar" onClick={onClose}><X/></button></header>
 <div className="modal-body">{kind==='bean'?<div className="form-grid">{[['name','Nombre del café'],['roaster','Tostador'],['origin','Origen / región'],['producer','Finca / productor'],['variety','Variedad'],['process','Proceso'],['altitude','Altura (m)'],['roastDate','Fecha de tueste']].map(([key,label])=><label key={key}>{label}<input name={key} required={['name','roaster','origin'].includes(key)} type={key==='roastDate'?'date':'text'} defaultValue={b?.[key as keyof Bean]||''} maxLength={160}/></label>)}<label className="full">Notas del tostador<textarea name="notes" defaultValue={b?.notes} maxLength={3000}/></label></div>:<><div className="form-grid"><label className="full">Café<select value={r.beanId} onChange={e=>setR({...r,beanId:e.target.value})} required>{beans.map(b=><option key={b.id} value={b.id}>{b.name} · {b.roaster}</option>)}</select></label><label>Método<select value={r.method} onChange={e=>setR({...r,method:e.target.value})}>{methods.map(m=><option key={m}>{m}</option>)}</select></label><label>Fecha<input required type="date" value={r.date} onChange={e=>setR({...r,date:e.target.value})}/></label>{number('dose','Café seco (g)',0.1,200,0.1)}{r.method!=='Espresso'&&number('water','Agua utilizada (g)',1,3000,0.1)}{number('output','Bebida obtenida (g)',0.1,3000,0.1)}{number('seconds','Tiempo total (s)',1,7200)}{number('temperature','Temperatura (°C)',1,100,0.1)}{number('clicks','Ajuste / clics',0,500,0.1)}<label className="full">Modelo de molino<input required value={r.grinder} onChange={e=>setR({...r,grinder:e.target.value})} placeholder="Ej. Comandante C40" maxLength={160}/></label></div><p className="ratio-preview">Ratio calculado <strong>1 : {Number(r.dose)>0?ratio(r):'—'}</strong><small>{r.method==='Espresso'?'Café : bebida obtenida':'Café : agua utilizada'}</small></p><div className="score-control"><label>Resultado en taza <strong>{r.score} / 10</strong><input type="range" min="1" max="10" step="0.5" value={r.score} onChange={e=>setR({...r,score:Number(e.target.value)})}/></label></div><div className="form-grid">{(['acidity','sweetness','body','finish'] as const).map((k,i)=><label key={k}>{['Acidez','Dulzor','Cuerpo','Postgusto'][i]} <span className="float-right">{r[k]}</span><input type="range" min="1" max="10" value={r[k]} onChange={e=>setR({...r,[k]:Number(e.target.value)})}/></label>)}</div><label>Vertidos y sensaciones<textarea value={r.notes} onChange={e=>setR({...r,notes:e.target.value})} placeholder="Bloom, secuencia de vertidos, textura, aromas…" maxLength={6000}/></label></>}</div>
 <footer className="modal-footer">{onDelete&&<button type="button" className="text-button" onClick={onDelete}>Eliminar</button>}<button type="button" className="button secondary" onClick={onClose}>Cancelar</button><button className="button" type="submit">Guardar {kind==='bean'?'café':'receta'}</button></footer></form></dialog>
}
