'use client';
import {useState} from 'react';
import type {Grinder} from '@/lib/coffee';
export default function GrinderSettings({grinders,onSave}:{grinders:Grinder[];onSave:(g:Grinder[])=>boolean}){
 const [editing,setEditing]=useState<Grinder|null>(null);
 const [adding,setAdding]=useState(false);
 return <section className="panel"><div className="section-heading"><h2>Mis molinos</h2><button className="button secondary" onClick={()=>{setEditing(null);setAdding(true)}}>Añadir molino</button></div><p>Guarda tu equipo y selecciona el perfil al registrar una taza. Los ajustes solo son comparables dentro del mismo molino y escala.</p>
 {grinders.map(g=><article className="grinder-item" key={g.id}><div><strong>{g.name}</strong><small>{g.unit}</small><p>{g.notes}</p></div><div className="actions"><button className="text-button" onClick={()=>{setEditing(g);setAdding(true)}} aria-label={'Editar '+g.name}>Editar</button><button className="text-button" onClick={()=>{if(confirm('¿Eliminar este perfil? Las recetas conservarán el molino y ajuste originales.')){if(onSave(grinders.filter(x=>x.id!==g.id))&&editing?.id===g.id)setAdding(false)}}} aria-label={'Eliminar '+g.name}>Eliminar</button></div></article>)}
 {!grinders.length&&!adding&&<p>No tienes perfiles todavía. Tus recetas anteriores conservan el nombre de su molino.</p>}
 {adding&&<form key={editing?.id||'new'} className="grinder-editor" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const next:Grinder={id:editing?.id||crypto.randomUUID(),name:String(f.get('name')).trim(),unit:String(f.get('unit')).trim(),notes:String(f.get('notes')).trim()};if(!next.name||!next.unit)return;if(onSave(editing?grinders.map(g=>g.id===editing.id?next:g):[...grinders,next]))setAdding(false)}}><h3>{editing?'Editar molino':'Nuevo molino'}</h3><div className="form-grid"><label>Nombre y modelo<input name="name" required maxLength={160} defaultValue={editing?.name} placeholder="Comandante C40 · estándar"/></label><label>Unidad del ajuste<input name="unit" required maxLength={40} defaultValue={editing?.unit||'clics'} placeholder="Clics, posiciones, vueltas…"/></label></div><label>Notas del equipo<textarea name="notes" maxLength={2000} defaultValue={editing?.notes} placeholder="Punto cero, muelas, calibración…"/></label><p>Si cambias las muelas o la escala, crea otro perfil para distinguir los ajustes.</p><div className="actions"><button className="button" type="submit">Guardar molino</button><button className="button secondary" type="button" onClick={()=>setAdding(false)}>Cancelar</button></div></form>}
 </section>
}
